#!/usr/bin/env python3
# -*- coding: utf8 -*-

import sys
import signal

from smserver import conf, server

def main():
    config = conf.Conf(*sys.argv[1:])
    serv = server.StepmaniaServer(config)

    try:
        signal.signal(signal.SIGTERM, lambda *_: sys.exit())
        signal.signal(signal.SIGHUP, lambda *_: serv.reload())
    except AttributeError:
        pass

    try:
        serv.start()
    except (KeyboardInterrupt, SystemExit):
        serv.stop()
        sys.exit()

if __name__ == "__main__":
    main()
