#!/usr/bin/env python3
# -*- coding: utf8 -*-

import sys

from smserver import conf, server

def main():
    config = conf.Conf(*sys.argv[1:])
    serv = server.StepmaniaServer(config)
    try:
        serv.start()
    except (KeyboardInterrupt, SystemExit):
        serv.stop()
        sys.exit()

if __name__ == "__main__":
    main()
