#!/usr/bin/env python3
# -*- coding: utf8 -*-

import sys

from smserver import conf, server

def main():
    config = conf.Conf(*sys.argv[1:])
    server.StepmaniaServer(config).start()


if __name__ == "__main__":
    main()
